import type { QueueIncident } from './types';

export const PRIMARY_DEMO_INCIDENT: QueueIncident = {
  id: 'inc-demo-001',
  priority: 'critical',
  status: 'reviewing',
  title: 'Coordinated repost wave flooding new queue',
  itemType: 'post',
  reportCount: 22,
  queueAgeMinutes: 64,
  suspectedRuleArea: 'Spam and repost policy',
  whySurfaced: [
    'High report volume across posts with matching titles and domains',
    'Related items arrived inside one moderation window',
    'Queue age is rising while new duplicates continue to appear',
  ],
  userContextSummary:
    'Demo cluster of low-context accounts posting similar links. No real usernames or subreddit data are included.',
  relatedItemCount: 13,
  rationaleDraft:
    'Treat as a likely repost wave. Review the grouped posts together, confirm source similarity, then decide whether a bulk response is appropriate in a later sprint.',
  createdAt: '2026-05-14T08:20:00.000Z',
  updatedAt: '2026-05-14T09:24:00.000Z',
  tags: ['duplicate-wave', 'link-cluster', 'time-sensitive'],
  signalStrength: 'high',
  recommendedReviewAction: 'Inspect the grouped posts before clearing individual reports.',
  confidenceLabel: 'high',
  timeline: [
    {
      id: 'inc-demo-001-t1',
      label: 'First seen',
      detail: 'Initial reported post entered the demo queue.',
      occurredAt: '2026-05-14T08:20:00.000Z',
    },
    {
      id: 'inc-demo-001-t2',
      label: 'Reports accumulated',
      detail: 'Report volume crossed the Sprint 6 critical demo threshold.',
      occurredAt: '2026-05-14T08:48:00.000Z',
    },
    {
      id: 'inc-demo-001-t3',
      label: 'Related items grouped',
      detail: 'Thirteen related queue items were attached to the incident.',
      occurredAt: '2026-05-14T09:18:00.000Z',
    },
  ],
};

export const DEMO_INCIDENTS: QueueIncident[] = [
  PRIMARY_DEMO_INCIDENT,
  {
    id: 'inc-demo-002',
    priority: 'high',
    status: 'open',
    title: 'Comment thread receiving duplicate civility reports',
    itemType: 'comment',
    reportCount: 15,
    queueAgeMinutes: 42,
    suspectedRuleArea: 'Civility and personal attacks',
    whySurfaced: [
      'Several reports point to the same thread branch',
      'Reports are clustered around one escalating exchange',
      'Reviewing the branch can resolve several queue items together',
    ],
    userContextSummary:
      'Demo participants in a heated thread branch with no real account data.',
    relatedItemCount: 8,
    rationaleDraft:
      'Review the visible exchange in context before deciding whether reminders, removals, or no action are appropriate in a later sprint.',
    createdAt: '2026-05-14T08:44:00.000Z',
    updatedAt: '2026-05-14T09:18:00.000Z',
    tags: ['thread-branch', 'heated-exchange', 'context-needed'],
    signalStrength: 'high',
    recommendedReviewAction: 'Open the thread branch and review the exchange as one case.',
    confidenceLabel: 'medium',
    timeline: [
      {
        id: 'inc-demo-002-t1',
        label: 'First seen',
        detail: 'First civility report arrived on the thread branch.',
        occurredAt: '2026-05-14T08:44:00.000Z',
      },
      {
        id: 'inc-demo-002-t2',
        label: 'Branch clustered',
        detail: 'Eight related comments were grouped for moderator context.',
        occurredAt: '2026-05-14T09:05:00.000Z',
      },
    ],
  },
  {
    id: 'inc-demo-003',
    priority: 'high',
    status: 'open',
    title: 'Rapid reports on suspected brigading replies',
    itemType: 'user',
    reportCount: 18,
    queueAgeMinutes: 31,
    suspectedRuleArea: 'Community interference',
    whySurfaced: [
      'Reports mention coordinated arrival patterns',
      'Several demo accounts appear across related replies',
      'Signal strength is high but enforcement remains disabled',
    ],
    userContextSummary:
      'Demo-only user context summarizing repeated arrivals across a small group of replies.',
    relatedItemCount: 11,
    rationaleDraft:
      'Review arrival timing and reply context. Do not infer intent from report volume alone.',
    createdAt: '2026-05-14T08:58:00.000Z',
    updatedAt: '2026-05-14T09:29:00.000Z',
    tags: ['coordination-signal', 'reply-wave', 'needs-context'],
    signalStrength: 'high',
    recommendedReviewAction: 'Inspect related replies and preserve human review notes.',
    confidenceLabel: 'medium',
    timeline: [
      {
        id: 'inc-demo-003-t1',
        label: 'Spike detected',
        detail: 'Mock reports increased across related replies.',
        occurredAt: '2026-05-14T09:02:00.000Z',
      },
      {
        id: 'inc-demo-003-t2',
        label: 'Review pending',
        detail: 'Incident remains queued for moderator context review.',
        occurredAt: '2026-05-14T09:29:00.000Z',
      },
    ],
  },
  {
    id: 'inc-demo-004',
    priority: 'medium',
    status: 'open',
    title: 'Repeated link quality reports from same domain',
    itemType: 'domain',
    reportCount: 9,
    queueAgeMinutes: 27,
    suspectedRuleArea: 'Link quality review',
    whySurfaced: [
      'Domain appears in multiple queue items',
      'Reports are low severity but repeated',
      'Grouped review avoids clearing duplicate reports one by one',
    ],
    userContextSummary:
      'Demo domain summary only. No real domains or external reputation checks are used.',
    relatedItemCount: 6,
    rationaleDraft:
      'Review whether linked posts share low-quality patterns before taking any later sprint action.',
    createdAt: '2026-05-14T09:01:00.000Z',
    updatedAt: '2026-05-14T09:28:00.000Z',
    tags: ['domain-repeat', 'link-review'],
    signalStrength: 'medium',
    recommendedReviewAction: 'Check grouped links for pattern consistency.',
    confidenceLabel: 'medium',
    timeline: [
      {
        id: 'inc-demo-004-t1',
        label: 'Domain repeated',
        detail: 'Six related queue items were grouped by demo domain signal.',
        occurredAt: '2026-05-14T09:22:00.000Z',
      },
    ],
  },
  {
    id: 'inc-demo-005',
    priority: 'medium',
    status: 'reviewing',
    title: 'Megathread off-topic reports need batch context',
    itemType: 'comment',
    reportCount: 11,
    queueAgeMinutes: 36,
    suspectedRuleArea: 'Off-topic discussion',
    whySurfaced: [
      'Reports are concentrated in one megathread segment',
      'Related items share the same suspected rule area',
      'Moderator can review the segment instead of isolated comments',
    ],
    userContextSummary:
      'Demo segment summary for off-topic comments in a single discussion area.',
    relatedItemCount: 7,
    rationaleDraft:
      'Review the megathread segment and decide whether a moderator note would resolve the pattern.',
    createdAt: '2026-05-14T08:52:00.000Z',
    updatedAt: '2026-05-14T09:21:00.000Z',
    tags: ['megathread', 'off-topic', 'batch-review'],
    signalStrength: 'medium',
    recommendedReviewAction: 'Review the segment as a batch before clearing reports.',
    confidenceLabel: 'high',
    timeline: [
      {
        id: 'inc-demo-005-t1',
        label: 'Segment grouped',
        detail: 'Related comments were grouped under one review context.',
        occurredAt: '2026-05-14T09:10:00.000Z',
      },
    ],
  },
  {
    id: 'inc-demo-006',
    priority: 'medium',
    status: 'escalated',
    title: 'Potential personal information mention requires careful review',
    itemType: 'post',
    reportCount: 6,
    queueAgeMinutes: 58,
    suspectedRuleArea: 'Privacy and safety',
    whySurfaced: [
      'Reports reference a sensitive information concern',
      'Queue age is elevated for a safety-adjacent rule area',
      'Escalated status is demo-only and does not notify anyone',
    ],
    userContextSummary:
      'Demo safety-adjacent summary. No real personal information is present.',
    relatedItemCount: 2,
    rationaleDraft:
      'Review carefully and avoid automated assumptions. Sprint 6 does not escalate or notify externally.',
    createdAt: '2026-05-14T08:26:00.000Z',
    updatedAt: '2026-05-14T09:24:00.000Z',
    tags: ['privacy-review', 'safety-adjacent', 'careful-review'],
    signalStrength: 'medium',
    recommendedReviewAction: 'Prioritize careful human review before any future action path.',
    confidenceLabel: 'low',
    timeline: [
      {
        id: 'inc-demo-006-t1',
        label: 'Escalation placeholder',
        detail: 'Marked escalated in demo data only; no external escalation occurred.',
        occurredAt: '2026-05-14T09:24:00.000Z',
      },
    ],
  },
  {
    id: 'inc-demo-007',
    priority: 'low',
    status: 'open',
    title: 'Low-volume flair misuse reports across help posts',
    itemType: 'post',
    reportCount: 4,
    queueAgeMinutes: 19,
    suspectedRuleArea: 'Flair and formatting',
    whySurfaced: [
      'Reports share one lightweight rule area',
      'Grouped review can clear low-risk items quickly',
      'No urgent safety signal is present in demo data',
    ],
    userContextSummary:
      'Demo help-post cluster with repeated flair reports and low severity.',
    relatedItemCount: 4,
    rationaleDraft:
      'Review as a quick cleanup batch after higher-priority incidents.',
    createdAt: '2026-05-14T09:07:00.000Z',
    updatedAt: '2026-05-14T09:26:00.000Z',
    tags: ['flair', 'formatting', 'quick-clear'],
    signalStrength: 'low',
    recommendedReviewAction: 'Defer until critical and high incidents are reviewed.',
    confidenceLabel: 'high',
    timeline: [
      {
        id: 'inc-demo-007-t1',
        label: 'Grouped for cleanup',
        detail: 'Low-risk reports were grouped for later review.',
        occurredAt: '2026-05-14T09:26:00.000Z',
      },
    ],
  },
  {
    id: 'inc-demo-008',
    priority: 'low',
    status: 'resolved',
    title: 'Resolved demo cluster for repeated title formatting reports',
    itemType: 'post',
    reportCount: 5,
    queueAgeMinutes: 14,
    suspectedRuleArea: 'Title formatting',
    whySurfaced: [
      'Reports were duplicates across similar title issues',
      'Demo resolved state demonstrates metrics without real action',
      'No moderation action was performed by Queue Sentinel',
    ],
    userContextSummary:
      'Resolved demo incident retained for Sprint 6 metric cards.',
    relatedItemCount: 5,
    rationaleDraft:
      'Resolved in demo state only. This proves metrics can include completed review sessions later.',
    createdAt: '2026-05-14T08:38:00.000Z',
    updatedAt: '2026-05-14T09:12:00.000Z',
    tags: ['resolved-demo', 'title-formatting'],
    signalStrength: 'low',
    recommendedReviewAction: 'No current review needed in demo state.',
    confidenceLabel: 'high',
    timeline: [
      {
        id: 'inc-demo-008-t1',
        label: 'Demo resolved',
        detail: 'Incident is resolved only in demo data.',
        occurredAt: '2026-05-14T09:12:00.000Z',
      },
    ],
  },
  {
    id: 'inc-demo-009',
    priority: 'high',
    status: 'open',
    title: 'Queue age spike on marketplace-style solicitation reports',
    itemType: 'comment',
    reportCount: 12,
    queueAgeMinutes: 73,
    suspectedRuleArea: 'Solicitation and self-promotion',
    whySurfaced: [
      'Queue age is the highest in the current demo data',
      'Reports mention repeated solicitation language',
      'Several related comments are attached for context',
    ],
    userContextSummary:
      'Demo-only summary of repeated solicitation-style comments.',
    relatedItemCount: 6,
    rationaleDraft:
      'Review the stale queue items first if the team is optimizing for backlog age.',
    createdAt: '2026-05-14T08:05:00.000Z',
    updatedAt: '2026-05-14T09:18:00.000Z',
    tags: ['stale-queue', 'solicitation', 'self-promo'],
    signalStrength: 'high',
    recommendedReviewAction: 'Review soon because queue age is elevated.',
    confidenceLabel: 'medium',
    timeline: [
      {
        id: 'inc-demo-009-t1',
        label: 'Age threshold crossed',
        detail: 'Queue age rose above one hour in demo data.',
        occurredAt: '2026-05-14T09:05:00.000Z',
      },
    ],
  },
  {
    id: 'inc-demo-010',
    priority: 'medium',
    status: 'open',
    title: 'User profile review requested after repeated queue touches',
    itemType: 'user',
    reportCount: 8,
    queueAgeMinutes: 22,
    suspectedRuleArea: 'Pattern review',
    whySurfaced: [
      'Same demo user entity appears across multiple item reports',
      'Reports are varied but share enough context for one review pass',
      'Human review is required before interpreting the pattern',
    ],
    userContextSummary:
      'Demo profile-level summary based on repeated queue touches, with no real identity data.',
    relatedItemCount: 5,
    rationaleDraft:
      'Use the case card as a context aid only. Sprint 6 must not recommend account action.',
    createdAt: '2026-05-14T09:04:00.000Z',
    updatedAt: '2026-05-14T09:26:00.000Z',
    tags: ['profile-context', 'pattern-review'],
    signalStrength: 'medium',
    recommendedReviewAction: 'Open related items before drawing conclusions from the pattern.',
    confidenceLabel: 'low',
    timeline: [
      {
        id: 'inc-demo-010-t1',
        label: 'Pattern grouped',
        detail: 'Repeated queue touches were grouped for moderator context.',
        occurredAt: '2026-05-14T09:26:00.000Z',
      },
    ],
  },
];
