import type { RedditReadonlyInput } from './types';

export const PLAYTEST_READONLY_INPUTS: RedditReadonlyInput[] = [
  {
    itemId: 't3_playtest_repost_1',
    itemType: 'post',
    subredditName: 'queue_sentinel_lab',
    authorKey: 'playtest-author-a',
    domainKey: 'playtest-links.invalid',
    suspectedRuleArea: 'Spam and repost policy',
    reportReason: 'duplicate playtest link',
    createdAt: '2026-05-15T08:10:00.000Z',
    receivedAt: '2026-05-15T08:15:00.000Z',
    safeExcerpt: 'Synthetic playtest post metadata only.',
    tags: ['playtest', 'duplicate-wave'],
  },
  {
    itemId: 't3_playtest_repost_2',
    itemType: 'post',
    subredditName: 'queue_sentinel_lab',
    authorKey: 'playtest-author-b',
    domainKey: 'playtest-links.invalid',
    suspectedRuleArea: 'Spam and repost policy',
    reportReason: 'matching domain report',
    createdAt: '2026-05-15T08:22:00.000Z',
    receivedAt: '2026-05-15T08:26:00.000Z',
    safeExcerpt: 'Synthetic playtest post metadata only.',
    tags: ['playtest', 'domain-repeat'],
  },
  {
    itemId: 't1_playtest_thread_1',
    itemType: 'comment',
    subredditName: 'queue_sentinel_lab',
    authorKey: 'playtest-author-c',
    threadKey: 'playtest-thread-a',
    suspectedRuleArea: 'Civility and personal attacks',
    reportReason: 'heated exchange',
    createdAt: '2026-05-15T08:31:00.000Z',
    receivedAt: '2026-05-15T08:34:00.000Z',
    safeExcerpt: 'Synthetic playtest comment metadata only.',
    tags: ['playtest', 'thread-branch'],
  },
  {
    itemId: 't1_playtest_thread_2',
    itemType: 'comment',
    subredditName: 'queue_sentinel_lab',
    authorKey: 'playtest-author-d',
    threadKey: 'playtest-thread-a',
    suspectedRuleArea: 'Civility and personal attacks',
    reportReason: 'same branch report',
    createdAt: '2026-05-15T08:35:00.000Z',
    receivedAt: '2026-05-15T08:38:00.000Z',
    safeExcerpt: 'Synthetic playtest comment metadata only.',
    tags: ['playtest', 'context-needed'],
  },
  {
    itemId: 't3_playtest_privacy_1',
    itemType: 'post',
    subredditName: 'queue_sentinel_lab',
    authorKey: 'playtest-author-e',
    suspectedRuleArea: 'Privacy and safety',
    reportReason: 'careful privacy review',
    createdAt: '2026-05-15T08:41:00.000Z',
    receivedAt: '2026-05-15T08:47:00.000Z',
    safeExcerpt: 'Synthetic privacy-adjacent metadata only.',
    tags: ['playtest', 'privacy-review'],
  },
];
